import { User } from 'firebase/auth';

export type UserRole = 'admin' | 'employee' | null;
export const Months = [
    'January', 'February', 'March', 'April', 'May', 'June',
    'July', 'August', 'September', 'October', 'November', 'December'
];
export type Month = typeof Months[number];

export interface AuthContextType {
    user: User | null;
    role: UserRole;
    loading: boolean;
}

export interface AppUser {
    email: string,
    name: string,
    role: UserRole;
}

// Chat Message are between at least one user, and the admin. 
export interface ChatMessage {
    id: string; // Make id optional as it will be generated by Firestore
    message: string;
    sender: string; // id
    receiver: string[]; //ids
    reference: string; //id of reservation or task
    timestamp: Date;
}

// Reservations extend one day and have a prefilled start and end time.
// Visible to all users connected to DB, displayed.  
export interface Reservation extends dbItem {
    numberOfPeople: number,
    contact?: string[],
}

export interface Task extends dbItem {
    assignedTo: string; // id
    reference?: string; // id of reservation or task
}

// Tasks are created by admins and assigned to users
// Tasks are only visible 
export interface dbItem {
    id: string;
    name: string; // Name of task
    dateStart: Date,
    dateEnd: Date,
    comment?: string,
}
